
# Assignment 1 (PS1)
Applied Machine Learning - SDU (Spring 2021)<br>
Instructor: Rahman Peimankar (abpe@mmmi.sdu.dk)

Due: February 25, 11:00.

The goal of this assignment is to revise the learning of the topics in Lesson 2 and Lesson 3, which are Python basics (SciPy, NumPy, Pandas, and Matplotlib) plus introduction to supervised learning.

# Part 1: Numpy

In [17]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy as np

Q1. Return the numpy version number.

In [23]:
def numpyImport():
    # YOUR CODE HERE
    return f"Numpy version: {np.__version__}"
print(numpyImport())
    #raise NotImplementedError()

Numpy version: 1.20.3


Q2. Create a 1D numpy array of numbers from 0 to 50.

In [34]:
def createArray():
    length = 50
    # YOUR CODE HERE
    return np.arange(51) # An array of 0 to 50 is 51 entries. 
    #raise NotImplementedError()
print(createArray())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


Q3. Create a 3×3 numpy array of all True’s

In [49]:
def createArrayBoolean():
    # YOUR CODE HERE
    return np.ones((3, 3), dtype=bool)
print(createArrayBoolean())
   # raise NotImplementedError()

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q4. Replace all odd numbers in the 1D array (length=50) with -1.

In [78]:
def replaceOdd():
    '''
    This function gets an array of size 50. 
    Then replace the odd numbers with -1 and return newArr as output.
    '''
    length = 50
    arr = np.arange(length)
    newArr = arr
    for each in newArr:
        if each % 2:
            newArr[each] = -1 
    # YOUR CODE HERE
   # raise NotImplementedError()
    return newArr
print (replaceOdd())

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1
 24 -1 26 -1 28 -1 30 -1 32 -1 34 -1 36 -1 38 -1 40 -1 42 -1 44 -1 46 -1
 48 -1]


Q5. Convert a 1D array to a 2D array with 2 rows.

In [79]:
def reshapeArray():
    arr = np.arange(10)
    return np.reshape(arr,(5,2))
    #raise NotImplementedError()
print(reshapeArray())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q6. Stack arrays a and b vertically.

In [84]:
def stackArray():
    a = np.arange(10).reshape(2,-1)
    b = np.repeat(1, 10).reshape(2,-1)
    print(a)
    print("\n")
    print(b)
    print("\n")
    return np.vstack((a,b))
    
    # YOUR CODE HERE
    #raise NotImplementedError()
print(stackArray())

[[0 1 2 3 4]
 [5 6 7 8 9]]


[[1 1 1 1 1]
 [1 1 1 1 1]]


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Part 2: Pandas

In [4]:
import pandas as pd

Q7. Take a dictionary as input and create DataFrame namely **df**. 

In [6]:
def createDF():
    my_dict = {'A': [1, 4, 7], 'B': [2, 5, 8], 'C': [3, 6, 9]}
    # YOUR CODE HERE
    df = pd.DataFrame.from_dict(my_dict)
    #raise NotImplementedError()
    return df
print(createDF())

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


Q8. Complete the function below to access the value that is at index 2, in column 'A'. There are different solutions for this task. You may use 'loc', 'iloc', 'at', or 'iat' methods in Pandas.

In [31]:
def indexDF():
    df = createDF()
    value = df["A"].loc[2] # index
    
    #raise NotImplementedError()
    return value
print(indexDF())

7


Q9. Select the first row of the above dataframe.

In [24]:
def selectRowDF():
    df = createDF()
    row = df.loc[0]
    #raise NotImplementedError()
    return row
print(selectRowDF())

A    1
B    2
C    3
Name: 0, dtype: int64


Q10. Select the second column of the above dataframe.

In [36]:
def selectColDF():
    df = createDF()
    col = df["B"]

    #raise NotImplementedError()
    return col
print(selectColDF())

0    2
1    5
2    8
Name: B, dtype: int64


Q11. Find the second largest value of 'patient 1' for test 'B' and return it as **secondLargest**.

In [3]:
import numpy as np
import pandas as pd



def nLargest():
    myList = []
    np.random.seed(1234)
    df = pd.DataFrame({'test': ['A', 'B', 'C'] * 3,
                       'patient 1': np.random.rand(9),
                       'patient 2': np.random.randint(0, 15, 9)})
    for each in range(len(df)):
        if df["test"].iloc[each] == "B":
            myList.append(df["patient 1"].loc[each])
    myList.sort(reverse=True)
    # YOUR CODE HERE
    return myList[0]

print(nLargest())

0.8018721775350193


Q12. Compute the mean of every test for patient 1. Return the result as a dataframe with columns named 'test' and 'patient 1'.

In [ ]:
from IPython.display import Image
Image(filename='fig1.jpg',width=100, height=100)

In [7]:
import statistics

def selectTest(df,test,List):
    for each in range(len(df)):
            if df["test"].iloc[each] == test:
                List.append(df["patient 1"].loc[each])
    return List
def groupMean():
    np.random.seed(1234)
    df = pd.DataFrame({'test': ['A', 'B', 'C'] * 3,
                       'patient 1': np.random.rand(9),
                       'patient 2': np.random.randint(0, 15, 9)})
    aList = []
    bList = []
    cList = []
    
    aList = selectTest(df,'A',aList)
    bList = selectTest(df,'B',bList)
    cList = selectTest(df,'C',cList)
    aMean = statistics.mean(aList)
    bMean = statistics.mean(bList)
    cMean = statistics.mean(cList)
    data = {"test":["A","B","C"],"patient 1":[aMean,bMean,cMean]}
    df_mean = pd.DataFrame(data)
    print(df_mean)
    # YOUR CODE HERE
    #raise NotImplementedError()
    return df_mean
groupMean()


  test  patient 1
0    A   0.417781
1    B   0.734652
2    C   0.556153


test  patient 1
0    A   0.417781
1    B   0.734652
2    C   0.556153

Q13. Merge the two dataframes df1 and df2 (defined in the function below) based on the 'patient' and 'blood sugar'.

In [ ]:
def mergeDF():
    np.random.seed(1234)
    df1 = pd.DataFrame({'patient': ['A', 'B', 'C'] * 3,
                        'blood sugar': ['high', 'medium', 'low'] * 3,
                        'platelet count': np.random.randint(150, 450, 9)})
    df2 = pd.DataFrame({'patient': ['A', 'C', 'D'] * 2,
                        'blood sugar': ['high', 'low'] * 3,
                        'platelet count': np.random.randint(150, 450, 6)})
    # YOUR CODE HERE
    raise NotImplementedError()
    return df_merged

# Part 3: Matplotlib

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

*%matplotlib inline* is the magic command to plot the graph within the notebook itself. 

In [ ]:
x = np.linspace(-1.4, 1.4, 30)
plt.plot(x, x, 'g--', x, x**2, 'r:', x, x**3, 'b^')
plt.show()

#### Q14. Change the line width, the dash style or the alpha level of the above plot. You can get help from the documentation. <br>
https://matplotlib.org/tutorials/introductory/pyplot.html

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Q15. Plot multiple figures using Matplotlib **subplot** method. You can use the numpy array **a** below to generate different arrays and plot a 2 by 2 subplot.  

In [ ]:
a = np.linspace(-1.4, 1.4, 30)
a1 = a
a2 = a*2
a3 = a*3
a4 = a*4

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

# Part 4: Supervised Learning
### k-Nearest Neighbors Implementation 
As we learnt in the lecture KNN is a very simple yet powerful technique to use in supervised learning problems. Here we would like to implement KNN from scratch instead of using scikit-learn package!<br>
In this exercis, you will use Iris Flower Dataset to predict the flower species given four different measurments as below:
* Sepal length in cm.
* Sepal width in cm.
* Petal length in cm.
* Petal width in cm.

But in order to implement KNN from scratch in Python, three steps should be considered:

1. Compute Euclidean Distance
2. Find Nearest Neighbors
3. Do the Predictions

**Step 1:** <br>
The straight line between two vectors (Euclidean distance) can be calculated using equation below:<br>

* $Euclidean Distance(a, b) = \sqrt{\sum_{i=1}^{n}(a_i-b_i)^2}$ <br>

where $a$ and $b$ are the first and the second vectors (rows of data) and $i$ is the index to each attribute (column in the dataset). **The smaller the value of Euclidean Distance, the more similar the two vetors are.** <br> 

Now, it is your turn to complete the function below to implement Euclidean Distance.<br>
**Improtant:** You are not allowed to use "*from sklearn.metrics import euclidean_distances*" ! 

In [ ]:
from math import sqrt

In [ ]:
def euclideanDistance(row1, row2):
    # YOUR CODE HERE
    raise NotImplementedError()
    return euclidean_distance

**Hint:** You may check your implementation by passing this toy dataset: <br>
dataset = [[1, 2], [3, 4]] <br>
The Euclidean distance between the two columns should be equal to 2.

In [ ]:
dataset = [[1, 2], [3, 4]]
row0 = dataset[0]
for row in dataset:
    euclidean_distance = euclideanDistance(row0, row)
    print(euclidean_distance)

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

**Step 2:**
* In order to find *k* nearest points for a new data sample, the Eudlidean distance between the the new sample and all the rows of the dataset should be first calculated (using the function in the previous step). Then, all the samples in the dataset should be sorted based on their distance to the new data. Finally, the top *k* can be returned as the most similar samples/neighbors. <br>
* This can be done by storing the index and the Euclidean distance of each sample of the dataset in a tuple (https://jakevdp.github.io/WhirlwindTourOfPython/06-built-in-data-structures.html) and sort the list of the tuples by their Euclidean distances and then extract the nearest neighbors. 
* Now it is your turn to complete the function below (*findNeighbors*) to implmenet these functionality. 

In [ ]:
def findNeighbors(train_data, test_sample, numNeighbors):
    distances = list()
    for train_row in train_data:
        dist = euclideanDistance(test_sample, train_row)
        distances.append((train_row, dist))
    # YOUR CODE HERE
    raise NotImplementedError()
    neighbors = list()
    for i in range(numNeighbors):
        # YOUR CODE HERE
        raise NotImplementedError()
    return neighbors

**Hint:** You may check your implementation by passing this toy dataset:<br>
dataset = [[2.8,2.6,1],[1.5,2.4,0],[1.1,2.8,0],[2.4,2.5,1]] (the last column represents the true classes or targets)<br>
As it is expected, the second row is the most similiar and the third row ([1.1,2.8,0]) is the second nearest neighbor to a new sample [1.55,2.44].

In [ ]:
dataset = [[2.8,2.6,1],
           [1.5,2.4,0],
           [1.1,2.8,0],
           [2.4,2.5,1]]
neighbors = findNeighbors(dataset, [1.55,2.44], numNeighbors=2)
for n in neighbors:
    print(n)

**Step 3:** 
<br>Now that we have found the nearest neighbors, we can use them to make predictions on the new samples. Since our problem is a classification task, we simply need to return the most representative class among the neighbors. For this purpose, we need to count the number of each class among the neighbors. 

Now it is your turn to complete the function below (makePrediction) to implmenet these functionality. You should output a

In [ ]:
def predictClassification(train_data, test_sample, numNeighbors):
    
    '''The inputs for this function are:
    1. train_data: the training dataset
    2. test_sample: the new test sample that we would like to make prediction for it.
    3. numNeighbors: number of neighbors used in the "findNeighbors" function.
    The output of this function is the predicted class for the test sample.'''
    
    neighbors = findNeighbors(train_data, test_sample, numNeighbors)
    # YOUR CODE HERE
    raise NotImplementedError()
    return predicted_class

**Hint:** You may check your implementation by passing this toy dataset:<br>
dataset = [[2.8,2.6,1],[1.5,2.4,0],[1.1,2.8,0],[2.4,2.5,1]]<br>
If we pass a new "test_sample" of [1.55,2.44], the "predict_classification" function should classify it as 0. (numNeighbors=2)

In [ ]:
dataset = [[2.8,2.6,1],
           [1.5,2.4,0],
           [1.1,2.8,0],
           [2.4,2.5,1]]
print('The the new test sample {} is predicted as class {}'.format([1.55,2.44], 
                                                                   predictClassification(dataset, [1.55,2.44], 2)))

**Put everything together:** Now we have all the elements for applying our own kNN algorithm on the *Iris Flower Dataset*. This should be done in the following steps:

a. Load the Iris Flower dataset using *scikit-learn*. (please name the loaded dataset as **data_iris**)<br>
b. Apply the three functions developed in the previous steps to find the 5 nearest neighbors ($K=5$) and make predictions on the test data.<br>
c. Report the accuracy of the kNN algorithm on the test dataset.<br>

In [ ]:
from sklearn.datasets import load_iris
# YOUR CODE HERE
raise NotImplementedError()

Let's split the loaded dataset (**data_iris**) into 80% and 20% of train and test sets, respectively.<br>
Please name the outputs of "*train_test_split*" as *X_train, X_test, y_train, y_test*. 

**Improtant:** You should set "*random_state=42*" for the "*train_test_split*" methods/function. Otherwise, your answer will be graded as wrong!

In [ ]:
from sklearn.model_selection import train_test_split
# YOUR CODE HERE
raise NotImplementedError()

Let's implement a function for our kNN algorithm, which outputs a list of predictions for all the test samples. 

In [ ]:
def kNearestNeighbors(train_data, train_target, test_data, test_target, numNeighbors):
    predictions = list()
    # these two lines add the train and test targets to the data. Please do not modify them!
    train = np.append(train_data, train_target.reshape(train_target.shape[0], 1), axis=1)
    test = np.append(test_data, test_target.reshape(test_target.shape[0], 1), axis=1)
    # YOUR CODE HERE
    raise NotImplementedError()
    return predictions

Complete the function below to calculate the accuracy of the kNN algorithm!

In [ ]:
def accCalculation(actual, predicted):
    '''This function gets the actual class labels and the predictions from "kNearestNeighbors" function as inputs. 
    The output is the accuracy in percentage.'''
    # YOUR CODE HERE
    raise NotImplementedError()
    return accuracy

# End of PS1.
# Thank you!